# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Water pH'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='roomhumidity',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Room Humidity'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='roomtemp',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Room Temperature'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='watertemp',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Water Temperature'),
        ),
    ]
