# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydash', '0002_auto_20170109_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(verbose_name='Measurement Date'),
        ),
    ]
